### ISSUE TITLE
BUG: I can't choose Format type and help text isn't displayed since version f061c1542b73565a2ee32a6ec95f2d4d64dce387

### ISSUE THREAD

**Issue by HannaTrotsenko** [elasticio/webhook-component#22]
STR:
1. Set Webhook component as trigger
2. Choose latest version
3. Click *Add sample manually* button
AR:
![image](https://user-images.githubusercontent.com/28867440/64856719-62bcf800-d62b-11e9-8f5a-cd5f6611864a.png)
ER:
![image](https://user-images.githubusercontent.com/28867440/64856799-86803e00-d62b-11e9-958f-41370712dd38.png)

**Comment by stas-fomenko** [comment]
@HannaTrotsenko In the current version (f061c15) the component got button `Generate Stub Sample`, so basically there is no need in previous functionality.
As I spoke to @ElBabbler - metadata has been changed, so platform "knows" that stub sample should be generated as JSON, so you can just generate it.
So, seems that it does not affect the component in a negative way

**Comment by jhorbulyk** [comment]
> In the current version (f061c15) the component got button Generate Stub Sample, so basically there is no need in previous functionality.

I'm not sure if I agree with this statement.  We've added additional functionality to the platform but there are cases where the existing functionality is still very usefull.  I would propose re-adding the `WebHookPayloadView` field.

**Comment by HannaTrotsenko** [comment]
no longer acceptable
