### ISSUE TITLE
HTTP Post with XML file as attachment is not working

### ISSUE THREAD

**Issue by HannaTrotsenko** [elasticio/webhook-component#9]
STR:
1. Create flow with Webhook-trigger
2. Start flow and send request with e.g. pdf file and Content type multipart/form-data

AR: 
```
{
    "error": "getaddrinfo ENOTFOUND steward.marathon.slave.mesos-app steward.marathon.slave.mesos-app:8200"
}
```
![pasted image at 2018_03_15 11_09 am](https://user-images.githubusercontent.com/28867440/37459859-0f0e6ee2-2852-11e8-9b9a-8a6d150a3c6a.png)

ER: The reply is 
```
{
    "requestId": "b3eb7e50eef7171caaa7a8481d152d8e",
    "message": "thank you"
}
```

**Comment by zuker** [comment]
Here https://github.com/elasticio/webhooks/blob/0dcb4f5beaef6f11987f92a7c24a64f7c1300357/lib/attachments.js#L35 
`put_url` (which is received from steward) has domain name `steward.marathon.slave.mesos-app` which is resolvable from silver only, but not smollet (where webhooks are run). If we sill configure steward to return `steward.marathon.slave.mesos` (resolvable inside smollet) it will break attachments for flow steps.

**Comment by drobiazko** [comment]
@maklastic @zuker do you have a solution in mind?

**Comment by drobiazko** [comment]
Issue moved to [elasticio/webhooks #74](https://github.com/elasticio/webhooks/issues/74) via [**ZenHub**](https://www.zenhub.com/)
